[tool.isort]
force_single_line = true
lines_after_imports = 2
force_sort_within_sections = true
known_first_party = "doxxie"
default_section = "THIRDPARTY"
skip = [".riot/", ".venv/"]
line_length = 120

[tool.black]
exclude = '''
  (
    /(
      \.venv.*
      | \.riot
    )/
  )
'''
