class ExposedClass2:
    def __init__(self) -> None: ...
    def public_method(self) -> None: ...

class ExposedClass3:
    def __init__(self) -> None: ...
    def public_method(self) -> ExposedClass4: ...

class ExposedClass4:
    def __init__(self) -> None: ...
    def public_method(self) -> None: ...

class ExposedClass5:
    def __init__(self) -> None: ...
    def public_method(self) -> None: ...

class ExposedClass6:
    def public_method(self) -> None: ...

class ExposedClass7:
    def public_method(self) -> None: ...

class ExposedClass9:
    def public_method(self) -> None: ...

class ExposedClass10:
    def public_method(self) -> None: ...

class ExposedClass11:
    def public_method(self) -> None: ...
