name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  check_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: install mypy
        run: pip install mypy
      - name: install doxxie
        run: pip install .
      - run: DOXXIE_INCLUDES=doxxie DOXXIE_DEBUG=1 DOXXIE_OUTFILE=.public_api_delta mypy --no-incremental doxxie/
      - run: diff .public_api .public_api_delta
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: install riot
        run: pip install riot==0.4
      - run: riot -v run -s black --check .
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: install riot
        run: pip install riot==0.4
      - run: riot -v run mypy
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: install riot
        run: pip install riot==0.4
      - run: riot -v run docs
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/_build
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: install riot
        run: pip install riot==0.4
      - run: riot -v run -s flake8
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install riot
        run: pip install riot==0.4
      - name: run tests
        run: riot -v run --python=${{ matrix.python-version }} test
