name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install mypy
        run: pip install git+git://github.com/python/mypy.git@66c2ac516305f194a9bc37c1ebf7f22d62d6141c
      - name: install doxxie
        run: pip install .
      - run: doxxie --public-api-only --output public_api doxxie
      - run: git diff --exit-code
      - run: pip install riot==0.5
      - run: riot -v run -s black --check .
      - run: riot -v run -s flake8
      - run: riot -v run -s mypy -- --exclude tests/comprehensive/public_api
      - run: riot -v run -s docs
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install mypy
        run: pip install git+git://github.com/python/mypy.git@66c2ac516305f194a9bc37c1ebf7f22d62d6141c
      - name: install doxxie
        run: pip install .
      - run: |
          cd tests/comprehensive
          doxxie --public-api-only --public-api-exclude pkg.internal --output public_api pkg
          git diff --exit-code
